/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  ChangeRoute,
  WrapperState,
} from './components/login-component/login-component';
import {
  WrapperState as WrapperState1,
} from './components/register-component/register-component';

export namespace Components {
  interface AuthComponent {
    'proxy': string;
    'setWrapperState': any;
  }
  interface LoginComponent {
    'changeRoute': ChangeRoute;
    'proxy': string;
    'wrapperState': WrapperState;
  }
  interface RegisterComponent {
    'changeRoute': ChangeRoute;
    'proxy': string;
    'wrapperState': WrapperState;
  }
}

declare global {


  interface HTMLAuthComponentElement extends Components.AuthComponent, HTMLStencilElement {}
  var HTMLAuthComponentElement: {
    prototype: HTMLAuthComponentElement;
    new (): HTMLAuthComponentElement;
  };

  interface HTMLLoginComponentElement extends Components.LoginComponent, HTMLStencilElement {}
  var HTMLLoginComponentElement: {
    prototype: HTMLLoginComponentElement;
    new (): HTMLLoginComponentElement;
  };

  interface HTMLRegisterComponentElement extends Components.RegisterComponent, HTMLStencilElement {}
  var HTMLRegisterComponentElement: {
    prototype: HTMLRegisterComponentElement;
    new (): HTMLRegisterComponentElement;
  };
  interface HTMLElementTagNameMap {
    'auth-component': HTMLAuthComponentElement;
    'login-component': HTMLLoginComponentElement;
    'register-component': HTMLRegisterComponentElement;
  }
}

declare namespace LocalJSX {
  interface AuthComponent extends JSXBase.HTMLAttributes<HTMLAuthComponentElement> {
    'proxy'?: string;
    'setWrapperState'?: any;
  }
  interface LoginComponent extends JSXBase.HTMLAttributes<HTMLLoginComponentElement> {
    'changeRoute'?: ChangeRoute;
    'proxy'?: string;
    'wrapperState'?: WrapperState;
  }
  interface RegisterComponent extends JSXBase.HTMLAttributes<HTMLRegisterComponentElement> {
    'changeRoute'?: ChangeRoute;
    'proxy'?: string;
    'wrapperState'?: WrapperState;
  }

  interface IntrinsicElements {
    'auth-component': AuthComponent;
    'login-component': LoginComponent;
    'register-component': RegisterComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


